<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>EmailLibrary</RootNamespace>
    <AssemblyName>EmailLibrary</AssemblyName>
    <Deterministic>true</Deterministic>
    <LangVersion>latest</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Core" Version="1.35.0" />
    <PackageReference Include="Azure.Identity" Version="1.10.3" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="1.1.1" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.56.0" />
    <PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" Version="4.56.0" />
    <PackageReference Include="Microsoft.IdentityModel.Abstractions" Version="6.35.0" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="6.35.0" />
    <PackageReference Include="Microsoft.IdentityModel.Logging" Version="6.35.0" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols" Version="6.35.0" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="6.35.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.35.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Buffers" Version="4.5.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.1" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="6.0.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.35.0" />
    <PackageReference Include="System.IO.FileSystem.AccessControl" Version="5.0.0" />
    <PackageReference Include="System.Memory" Version="4.5.4" />
    <PackageReference Include="System.Memory.Data" Version="1.0.2" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.5.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    <PackageReference Include="System.Runtime.InteropServices.RuntimeInformation" Version="4.3.0" />
    <PackageReference Include="System.Security.AccessControl" Version="6.0.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="4.7.0" />
    <PackageReference Include="System.Security.Permissions" Version="6.0.0" />
    <PackageReference Include="System.Security.Principal.Windows" Version="5.0.0" />
    <PackageReference Include="System.Text.Encodings.Web" Version="6.0.0" />
    <PackageReference Include="System.Text.Json" Version="4.7.2" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
  </ItemGroup>


  <ItemGroup>
    <Compile Include="Connection.cs" />
    <Compile Include="Model\Account.cs" />
    <Compile Include="Model\Email.cs" />
    <Compile Include="Model\EmailReceipt.cs" />
    <Compile Include="Model\Tags.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="app.config" />
    <None Include="Web References\AccountService\Account.datasource" />
    <None Include="Web References\AccountService\AccountWeb.wsdl" />
    <None Include="Web References\AccountService\Reference.map" />
    <None Include="Web References\AccountService\AccountWeb.disco" />
  </ItemGroup>

  <ItemGroup>
    <WebReferences Include="Web References\" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Connected Services\" />
  </ItemGroup>

</Project>